# Generated by Django 4.2.1 on 2023-07-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_addjob_user_alter_companyprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppllicationSubmition',
        ),
    ]
