# Generated by Django 4.2.1 on 2023-05-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyRegistration',
        ),
    ]
