# Generated by Django 4.2.1 on 2023-05-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_companyregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addjob',
            name='user',
        ),
    ]
