# Generated by Django 4.2.1 on 2023-07-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_can_login_and_more'),
        ('company', '0005_alter_addjob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
