# Generated by Django 4.2.1 on 2023-06-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_addproject_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addeducation',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='addexperience',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='addproject',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='addskills',
            old_name='user_profile',
            new_name='user',
        ),
    ]
