# Generated by Django 4.2.1 on 2023-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(choices=[('high school', 'High School'), ('higher secondary', 'Higher Secondary'), ('diploma', 'Diploma'), ('graduation', 'Graduation'), ('post graduation', 'Post Graduation'), ('phd', 'PhD'), ('others', 'Others')], max_length=255, null=True),
        ),
    ]
