# Generated by Django 4.2.1 on 2023-05-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='uname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='password',
            new_name='password1',
        ),
    ]
