# Generated by Django 4.2.1 on 2023-07-10 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delete_appllicationsubmition'),
        ('user', '0007_alter_addeducation_user_alter_addexperience_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(blank=True, null=True, upload_to='profile_images/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.addjob')),
            ],
        ),
    ]
